# Generated by Django 5.2.15 on 2026-06-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_company_id', models.IntegerField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('selected_circuit_id', models.CharField(blank=True, max_length=100)),
                ('nature_of_fault_id', models.IntegerField(blank=True, null=True)),
                ('ticket_id', models.CharField(blank=True, default='', max_length=50)),
                ('ticket_raised_on', models.CharField(blank=True, default='', max_length=30)),
                ('fault_label', models.CharField(blank=True, max_length=50)),
                ('otdr_applicable', models.BooleanField(null=True)),
                ('ticket_status_local', models.CharField(blank=True, default='', max_length=40)),
                ('otdr_from', models.CharField(blank=True, default='', max_length=200)),
                ('otdr_to', models.CharField(blank=True, default='', max_length=200)),
                ('otdr_value', models.CharField(blank=True, default='', max_length=50)),
                ('otdr_remark', models.CharField(blank=True, default='', max_length=500)),
                ('otdr_image1_path', models.CharField(blank=True, default='', max_length=500)),
                ('otdr_image1_url', models.TextField(blank=True, default='')),
                ('otdr_image2_url', models.TextField(blank=True, default='')),
                ('fault_side', models.CharField(blank=True, default='', max_length=20)),
                ('circuit_numeric_id', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('INIT', 'Awaiting greeting'), ('AWAIT_CIRCUIT_DIGITS', 'Awaiting last 4 digits of Circuit ID'), ('AWAIT_CIRCUIT_DIGITS_FOR_TICKET', 'Awaiting last 4 digits (ticket check)'), ('AWAIT_CIRCUIT_CONFIRM', 'Confirming matched circuit'), ('AWAIT_CIRCUIT_CONFIRM_FOR_TICKET', 'Confirming matched circuit (ticket check)'), ('MENU', 'Main Menu'), ('CIRCUIT_LIST', 'Showing Circuit List'), ('CIRCUIT_LIST_FOR_TICKET', 'Showing Circuit List for Ticket'), ('COMPLAINT_TYPE', 'Selecting Fault Type'), ('AWAIT_OTDR', 'Awaiting OTDR Yes/No'), ('AWAIT_OTDR_FROM', 'Awaiting OTDR From (source station)'), ('AWAIT_OTDR_TO', 'Awaiting OTDR To (destination station)'), ('AWAIT_OTDR_VALUE', 'Awaiting OTDR Value (reading in metres)'), ('AWAIT_REMARK', 'Awaiting Plain Remark'), ('AWAIT_OTDR_IMAGE', 'Awaiting First OTDR Image'), ('AWAIT_OTDR_IMAGE2', 'Awaiting Optional Second OTDR Image'), ('AWAIT_FAULT_SIDE_CHECK', 'Validating OTDR fault side'), ('AWAIT_RAISE_ANYWAY', 'Awaiting Raise Ticket Anyway? Yes/No'), ('DONE', 'Flow Complete')], default='INIT', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
