# Generated by Django 5.2.15 on 2026-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_whatsappmessage_whatsappsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='chatbot_handler',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
