# Generated by Django 5.2.15 on 2026-06-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_clientaccount_chatbot_handler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
        migrations.DeleteModel(
            name='WhatsAppSession',
        ),
        migrations.RemoveField(
            model_name='clientaccount',
            name='chatbot_handler',
        ),
    ]
