# Generated by Django 5.2.15 on 2026-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_whatsappmessage_whatsappsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bot_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conversation',
            name='bot_state',
            field=models.CharField(blank=True, default='INIT', max_length=50),
        ),
    ]
