# Generated by Django 5.2.15 on 2026-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_conversation_bot_metadata_conversation_bot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
