# Generated by Django 5.2.3 on 2026-06-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_conversation_phone_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('domain_linked_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_logo', models.FileField(blank=True, null=True, upload_to='meta_docs/logos/')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='meta_docs/verification/')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dedicated_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_facebook_account', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_password', models.CharField(blank=True, max_length=255, null=True)),
                ('international_card_available', models.BooleanField(default=False)),
                ('international_card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('international_card_image', models.FileField(blank=True, null=True, upload_to='meta_docs/cards/')),
                ('bot_use_case_brief', models.TextField(blank=True, null=True)),
                ('business_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_category', models.CharField(blank=True, max_length=100, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_registration', to='CRM.clientaccount')),
            ],
        ),
    ]
