# Generated by Django 5.2.3 on 2026-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_metaregistrationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaregistrationdetails',
            name='bot_use_case_document',
            field=models.FileField(blank=True, null=True, upload_to='meta_docs/use_cases/'),
        ),
    ]
