# Generated by Django 5.2.15 on 2026-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_metaregistrationdetails_bot_use_case_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='selected_circuit_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
