# Generated by Django 5.2.3 on 2026-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_whatsappsession_selected_circuit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_application',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_head',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_pump_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_selected_product',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='gs_specific_gravity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('INIT', 'Awaiting greeting'), ('AWAIT_CIRCUIT_DIGITS', 'Awaiting last 4 digits of Circuit ID'), ('AWAIT_CIRCUIT_DIGITS_FOR_TICKET', 'Awaiting last 4 digits (ticket check)'), ('AWAIT_CIRCUIT_CONFIRM', 'Confirming matched circuit'), ('AWAIT_CIRCUIT_CONFIRM_FOR_TICKET', 'Confirming matched circuit (ticket check)'), ('MENU', 'Main Menu'), ('CIRCUIT_LIST', 'Showing Circuit List'), ('CIRCUIT_LIST_FOR_TICKET', 'Showing Circuit List for Ticket'), ('COMPLAINT_TYPE', 'Selecting Fault Type'), ('AWAIT_OTDR', 'Awaiting OTDR Yes/No'), ('AWAIT_OTDR_FROM', 'Awaiting OTDR From (source station)'), ('AWAIT_OTDR_TO', 'Awaiting OTDR To (destination station)'), ('AWAIT_OTDR_VALUE', 'Awaiting OTDR Value (reading in metres)'), ('AWAIT_REMARK', 'Awaiting Plain Remark'), ('AWAIT_OTDR_IMAGE', 'Awaiting First OTDR Image'), ('AWAIT_OTDR_IMAGE2', 'Awaiting Optional Second OTDR Image'), ('AWAIT_FAULT_SIDE_CHECK', 'Validating OTDR fault side'), ('AWAIT_RAISE_ANYWAY', 'Awaiting Raise Ticket Anyway? Yes/No'), ('DONE', 'Flow Complete'), ('GS_INIT', 'GS: Awaiting greeting'), ('GS_MENU', 'GS: Main Menu'), ('GS_PRODUCTS', 'GS: Product List'), ('GS_PRODUCT_DETAIL', 'GS: Product Detail'), ('GS_AWAIT_CAPACITY', 'GS: Awaiting Capacity'), ('GS_AWAIT_HEAD', 'GS: Awaiting Head'), ('GS_AWAIT_APPLICATION', 'GS: Awaiting Application'), ('GS_AWAIT_PUMP_TYPE', 'GS: Awaiting Pump Type'), ('GS_AWAIT_SPECIFIC_GRAVITY', 'GS: Awaiting Specific Gravity'), ('GS_DONE', 'GS: Flow Complete')], default='INIT', max_length=50),
        ),
    ]
