# Generated by Django 5.2.15 on 2026-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_whatsappsession_gs_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvantikaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AvantikaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(upload_to='avantika/templates/')),
                ('name_x', models.IntegerField(default=100)),
                ('name_y', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='stage',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('qualifying', 'Qualifying'), ('complete', 'Complete'), ('human_handoff', 'Human Handoff'), ('Request Quotation', 'Request Quotation'), ('Get Price', 'Get Price'), ('Talk to Sales', 'Talk to Sales'), ('Exploring Menu', 'Exploring Menu')], default='greeting', max_length=30),
        ),
    ]
