# Generated by Django 5.2.15 on 2026-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_avantikacontact_avantikatemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikatemplate',
            name='font_size',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='avantikatemplate',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
