# Generated by Django 5.2.15 on 2026-07-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_avantikatemplate_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikatemplate',
            name='custom_message',
            field=models.TextField(default='[Name]'),
        ),
    ]
