# Generated by Django 5.2.3 on 2026-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_avantikacampaignhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikacampaignhistory',
            name='campaign_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
