# Generated by Django 5.2.3 on 2026-07-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_avantikacampaignhistory_campaign_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikacampaignhistory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avantikacampaignhistory',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avantikacampaignhistory',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.avantikacontact'),
        ),
    ]
