# Generated by Django 5.2.3 on 2026-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0018_avantikacampaignhistory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavratriRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_relation', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend')], max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pass_type', models.CharField(blank=True, max_length=100, null=True)),
                ('select_date', models.CharField(blank=True, max_length=100, null=True)),
                ('pass_quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
