# Generated by Django 5.2.3 on 2026-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_navratriregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navratriregistration',
            name='pass_type',
            field=models.CharField(blank=True, choices=[('single_day_pass', 'Single Day Pass'), ('9_day_pass', '9 Day Pass')], max_length=100, null=True),
        ),
    ]
