# Generated by Django 5.2.3 on 2026-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_alter_navratriregistration_pass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikacontact',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='navratriregistration',
            name='guardian_relation',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('husband', 'Husband'), ('wife', 'Wife'), ('legal guardian', 'Legal Guardian'), ('friend', 'Friend')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navratriregistration',
            name='pass_type',
            field=models.CharField(blank=True, choices=[('single_day_pass', 'Single Day Pass'), ('season_pass', 'Season Pass')], max_length=100, null=True),
        ),
    ]
