# Generated by Django 5.2.15 on 2026-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0021_avantikacontact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikatemplate',
            name='address_font_size',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='avantikatemplate',
            name='phone_font_size',
            field=models.IntegerField(default=45),
        ),
    ]
