# Generated by Django 5.0.4 on 2026-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_callsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='avantikatemplate',
            name='address_font',
            field=models.CharField(default='Montserrat-Medium.ttf', max_length=255),
        ),
        migrations.AddField(
            model_name='avantikatemplate',
            name='name_font',
            field=models.CharField(default='Montserrat-ExtraBold.ttf', max_length=255),
        ),
        migrations.AddField(
            model_name='avantikatemplate',
            name='phone_font',
            field=models.CharField(default='Montserrat-SemiBold.ttf', max_length=255),
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
    ]
